//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conjoint
    {
        public int IDConj { get; set; }
        public Nullable<int> IDAdherent { get; set; }
        public string Genre { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<System.DateTime> Naissance { get; set; }
        public string VOrig { get; set; }
        public string Portable { get; set; }
        public string Mail { get; set; }
        public string photo2 { get; set; }
    }
}
