//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coordonnees
    {
        public int IDCoord { get; set; }
        public Nullable<int> IDAdherent { get; set; }
        public string Adresse { get; set; }
        public string CP { get; set; }
        public string Ville { get; set; }
        public string TelFixe { get; set; }
        public string Portable { get; set; }
        public string Mail { get; set; }
        public string Commentaires { get; set; }
        public string Adresse2 { get; set; }
    }
}
