//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotisation
    {
        public int IDCotis { get; set; }
        public Nullable<int> IDAdherent { get; set; }
        public string AnneeCotis { get; set; }
        public Nullable<decimal> Montant { get; set; }
        public string ModePaie { get; set; }
        public string Commentaires { get; set; }
    }
}
