//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enfants
    {
        public int NumEnf { get; set; }
        public Nullable<int> IDConj { get; set; }
        public Nullable<int> IDAdherent { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<System.DateTime> Naissance { get; set; }
    }
}
