//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class associationEntities2 : DbContext
    {
        public associationEntities2()
            : base("name=associationEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_1> Table_1 { get; set; }
        public virtual DbSet<Adherent> Adherent { get; set; }
        public virtual DbSet<Conjoint> Conjoint { get; set; }
        public virtual DbSet<Coordonnees> Coordonnees { get; set; }
        public virtual DbSet<Cotisation> Cotisation { get; set; }
        public virtual DbSet<Enfants> Enfants { get; set; }
        public virtual DbSet<Villages_de_la_région> Villages_de_la_région { get; set; }
    }
}
